### ISSUE TITLE
Prevent sending of jobs with undefined jobStart

### ISSUE THREAD

**Issue by bwand** [IntegrationMatters/njams-sdk#2]
Currently, it is possible to create invalid log messages by not setting jobStart explicitly (using job.start() or setStartTime()). Therefore it is very easy to create erroneous messages. Since the SDK will be public we should anticipate this error by either creating a "fallback" jobStart on job creation or throwing an exception if jobStart is undefined.

Implementation Suggestion:
* Do NOT flush/send a Logmessage when jobStart is not set
* If Logmessage is finished and jobStart is not set throw an Exception

**Comment by krautenberg** [comment]
By default, a startTime is set when the job is created, but can always be overriden by setStartTime(). When job.start() is called and no startTime was set before, the startTime will be set to DateTimeUtility.now(), but the job can be flushed before without creating an error because of its default startTime. Nulls are not allowed! 

The startTime can now always be set, but the status changes have been changed aswell. When the job is created, it is in state CREATED. It can only leave this state if start() is called, that leads to a state change to RUNNING. Now the method setStatus() can be used aswell, but the status cannot be set to null or back to CREATED.

When the Job is in state CREATED, neither activities nor attributes can be set to the job. start() has to be called first. An NjamsSdkRuntimeException is thrown if addActivity/Attribute is called before start(). If flush() is invoked before start(), the job will be flushed, but with no activities and no attributes. If end() is called before start(), the job's status will be set to WARNING, but it will be flushed.
